Django_learning_2/Django_08_Baozhang_system/Django_08_Baozhang_system/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^', include('web.urls')),
]

Django_learning_2/Django_08_Baozhang_system/web/urls.py
from django.conf.urls import url
from .views import account
from .views import home

urlpatterns = [
    url(r'^register.html$', account.register),
    url(r'^login.html$', account.login),

    url(r'^check_code.html$', account.check_code),

    url(r'^home$', account.home),

    url(r'^(?P<site>\w+).html$', home.home),


]

Django_learning_2/Django_08_Baozhang_system/repository/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    """用户表"""
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    # nickname = models.CharField(verbose_name='昵称', max_length=32,)
    nickname = models.CharField(verbose_name='昵称', max_length=32, null=True)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像', null=True)

    # create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True, null=True)

    fans = models.ManyToManyField(
        verbose_name='儿子们',
        to='UserInfo',
        through='UserFans',
        related_name='f',
        through_fields=('user', 'follower')
    )

class UserFans(models.Model):
    """互粉关系表"""
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users', on_delete=models.CASCADE)
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid', related_name='followers', on_delete=models.CASCADE)
    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]

class Blog(models.Model):
    """博客信息"""
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    user = models.OneToOneField(to='UserInfo', to_field='nid', on_delete=models.CASCADE)


class Category(models.Model):
    """博主个人文章分类"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

class ArticleDetail(models.Model):
    """文章详细表"""
    content = models.TextField(verbose_name='文章内容')
    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid', on_delete=models.CASCADE)

class Tag(models.Model):
    """标签表"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

class Article(models.Model):
    """文章表"""
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)
    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True, on_delete=models.CASCADE)

    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "OpenStack"),
        (4, "GoLang"),
    ]

    article_type_id = models.IntegerField(choices=type_choices, default=None)

    tags = models.ManyToManyField(
        to='Tag',
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )


class Article2Tag(models.Model):
    """文章和标签的关系表"""
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to='Tag', to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

Django_learning_2/Django_08_Baozhang_system/web/views/home.py
from django.shortcuts import render, redirect, HttpResponse
from repository import models


def home(request, site):
    """博主个人首页"""
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)

    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num, strftime("%Y-%m", create_time) as ctime from repository_article group by strftime("%Y-%m", create_time)'
    )

    article_list = models.Article.objects.filter(blog=blog).order_by('-nid').all()

    return render(
        request,
        'home.html',
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list,
        }
    )

Django_learning_2/Django_08_Baozhang_system/templates/home.html
{% extends 'home_layout.html' %}

{% block content %}
    <div class="summary-list">
        {% for row in article_list %}
            <div class="summary-item">
                <a href="/{{ blog.site }}/{{ row.nid }}.html">{{ row.title }}</a>
            </div>

            <div class="summary-content">
                {{ row.summary }}
            </div>

            <div class="summary-footer">
                <span>{{ row.create_time|date:"Y-m-d H:i:s" }}</span>
                <span>{{ row.user.nickname }}</span>
                <span>阅读{{ row.read_count }}</span>
                <a>评论({{ row.comment_count }}</a>
                <a href="/backend/edit-article-{{ row.nid }}.html">编辑</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Django_learning_2/Django_08_Baozhang_system/templates/home_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>

    {% block css %}{% endblock %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.js"></script>
</head>
<body>
<div class="pg-header">
    <div class="title">{{ blog.title }}</div>
    <div class="menu-list">
        <a class="menu-item" href="/">首页</a>
        <a class="menu-item" href="/{{ blog.site }}.html">个人首页</a>
        <a class="menu-item" href="/backend/index.html">管理</a>
    </div>
</div>

<div class="pg-body">
    <div class="body-menu">
        <div class="notice-header">公告</div>
        <div class="notice-body">
            <ul>
                <li>昵称：{{ blog.user.nickname }}</li>
                <li>粉丝：{{ blog.user.fans.count }}</li>
                <li>关注：{{ blog.user.f.count }}</li>
                <li>邮箱：{{ blog.user.email }}</li>
            </ul>
            <div class="memo">
                愿我们在没有黑暗的地方相见
            </div>
        </div>
    </div>

    <div class="tags">
        <div class="tags-header">标签</div>
        <div class="tags-body">
            <ul>
                {% for tag in tag_list %}
                    <li><a href="/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="types">
        <div class="types-header">分类</div>
        <div class="type-body">
            <ul>
                {% for tag in category_list %}
                    <li><a href="/{{ blog.site }}/category/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="body-content">
        {% block content %}{% endblock %}
    </div>
</div>

{% block js %}{% endblock %}

</body>
</html>

Django_learning_2/Django_08_Baozhang_system/templates/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/edmure.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/account.css"/>
</head>
<body>
<div class="hg_background clearfix">
<div class="login">
    <div style="font-size: 25px; font-weight: bold;text-align: center;">
        用户登陆
    </div>
    <form id="fm" method="POST" action="/login.html">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">用户名</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="请输入用户名">
        </div>
        <div class="form-group">
            <label for="password">密码</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="请输入密码">
        </div>
        <div class="form-group">
            <label for="password">验证码</label>

            <div class="row">
                <div class="col-xs-7">
                    <input type="text" class="form-control" name="check_code" id="check_code" placeholder="请输入验证码">
                </div>
                <div class="col-xs-5">
                    <img id="check_code_img" src="/check_code.html">
                </div>
            </div>

        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="1" name="rmb"> 一个月内自动登陆
            </label>

            <div class="right">
                <a href="#">忘记密码？</a>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <a id="submit" class="btn btn-default">登 陆</a>
            </div>
            <div class="col-xs-9" style="padding-left: 0;">
                <div class="alert alert-danger hide">
                    <span style="padding: 0 5px 0 5px;display: inline-block;font-size: 14px">
                        <i class="fa fa-minus-circle" aria-hidden="true"></i>
                    </span>
                    <span id="error_msg" style="font-size: 12px;"></span>
                </div>
            </div>
        </div>
    </form>
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script type="text/javascript">
        $(function () {
            bindLogin();
        });
        function bindLogin() {
            $('#submit').click(function () {
                var $msg = $('#error_msg');
                $msg.parent().addClass('hide');
                $.ajax({
                    url: '/login.html',
                    type: 'POST',
                    data: $('#fm').serialize(),
                    dataType: 'JSON',
                    success: function (arg) {
                        if(arg.status){
                            location.href = '/home'
                        }else{
                            $msg.parent().removeClass('hide');
                            $msg.text(arg.message);
                            var img = $('#check_code_img')[0];
                            img.src = img.src + '?';
                            $('#password,#check_code').val('');
                        }

                    }
                })
            })
        }
    </script>
</div>
</div>
</body>
</html>

Django_learning_2/Django_08_Baozhang_system/templates/register.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/edmure.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/account.css"/>
    <style>

    </style>
</head>
<body>
<div class="hg_background clearfix">
<div class="register">
    <div style="font-size: 25px; font-weight: bold;text-align: center;">
        用户注册
    </div>
    <form id="fm" method="POST" action="/register.html">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">用户名</label>
            <input type="email" class="form-control" id="username" name="username" placeholder="请输入用户名">
        </div>
        <div class="form-group">
            <label for="email">邮箱</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="请输入邮箱地址">
        </div>
        <div class="form-group">
            <label for="password">密码</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码">
        </div>
        <div class="form-group">
            <label for="confirm_password">确认密码</label>
            <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="请重新输入密码">
        </div>

        <div class="form-group">
            <label for="check_code">验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    <input type="text" class="form-control" id="check_code" name="check_code" placeholder="请输入验证码">
                </div>
                <div class="col-xs-5">
                    <img src="/check_code.html">
                </div>
            </div>
        </div>

         <div class="row">
            <div class="col-xs-3">
                <a id="submit" class="btn btn-default">注 册</a>
            </div>
            <div class="col-xs-9" style="padding-left: 0;">
                <div class="alert alert-danger hide">
                    <span style="padding: 0 5px 0 5px;display: inline-block;font-size: 14px">
                        <i class="fa fa-minus-circle" aria-hidden="true"></i>
                    </span>
                    <span id="error_msg" style="font-size: 12px;"></span>
                </div>
            </div>
        </div>

    </form>
</div>
</div>
</body>
<script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
<script>
    $(function () {
        registerBtn();
    });

    function registerBtn() {
        $('#submit').click(function () {
                var $msg = $('#error_msg');
                $msg.parent().addClass('hide');
                $.ajax({
                    url: '/register.html',
                    type: 'POST',
                    data: $('#fm').serialize(),
                    dataType: 'JSON',
                    success: function (arg) {
                        if(arg.status){
                            location.href = '/login.html'
                        }else{
                            $msg.parent().removeClass('hide');
                            $msg.text(arg.message);
                            var img = $('#check_code_img')[0];
                            img.src = img.src + '?';
                            $('#password,#check_code').val('');
                        }

                    }
                })
            })
        }

</script>
</html>